name: Upload dataset to staging or production DB

on:
  workflow_dispatch:
    inputs: 
      dataset-folder:
        description: "Enter the relative path to the new dataset"
        required: true
      skip-per-cell-upload:
        type: boolean
        description: "Skip the file-info upload to save some processing time. Only select if this isn't the first time uploading the dataset, and there are no changes to per cell file-info"
        default: false
      database:
        description: "Please choose a database to upload dataset"
        type: choice
        default: "staging"
        options: 
        - staging
        - production

jobs: 
  process_dataset_to_staging: 
    name: Process Dataset to Stag
    runs-on: ubuntu-latest
    if: github.event.inputs.database == 'staging'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: echo "npm ci"
      - name: Process dataset to staging
        run: echo "process to stag"
        
  get_admins:
    runs-on: ubuntu-latest
    outputs:
      collaborators: ${{ steps.check_collaborator.outputs.text }}
    steps:
      - name: Get collaborators
        id: check_collaborator
        run: |
          response=$(curl --request GET \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --url https://api.github.com/repos/${{ github.repository }}/collaborators \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json')
          collaborators=$(echo "$response" | jq -r '.[] | select(.permissions.admin == true) | .login')
          text= ["a","b"]
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo text<<$EOF >> $GITHUB_OUTPUT
          echo "["a","b"]" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
          echo $collaborators
          
  process_dataset_to_production: 
    name: Process Dataset to Prod
    runs-on: ubuntu-latest
#     if: github.event.inputs.database == 'production' && github.ref == 'refs/heads/main'
    needs: get_admins
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: echo "npm ci"
      - name: Process dataset to production
        if: contains(needs.get_admins.outputs.text, github.triggering_actor)
        run: | 
          echo ${{ needs.get_admins.outputs.text }}
          echo "process to prod"
      - name: Not authorized to process dataset to production
        if: ${{ !contains(needs.get_admins.outputs.text, github.triggering_actor) }}
        run: |
          echo ${{ needs.get_admins.outputs.text }}
          echo "Failed to process dataset to production database. Please contact the owner of the repository to obtain the permission."
        
